### ISSUE TITLE
Can we put the original libwebp.podspec (not json format) here for maintain ?

### ISSUE THREAD

**Issue by dreampiggy** [SDWebImage/libwebp-Xcode#1]
See all the third party C/C++ image decoding library we used for custom decoder:

+ [libheif-Xcode](https://github.com/SDWebImage/libheif-Xcode)
+ [libbpg-Xcode](https://github.com/SDWebImage/libbpg-Xcode)
+ [libflif-Xcode](https://github.com/SDWebImage/libflif-Xcode)
+ [libx265-Xcode](https://github.com/SDWebImage/libx265-Xcode)
+ [libde265-Xcode](https://github.com/SDWebImage/libde265-Xcode)

They are contains the both Xcode project (using for Carthage or user who need the framework), and the podspec for CocoaPods.

Making the podspec public can make it easier for future maintain. Especially when you don't want to maintain the repo and need another people to take the relay.

I current could not find the original podspec files for https://cocoapods.org/pods/libwebp. Could you please upload it here ? @bpoplauschi

**Comment by bpoplauschi** [comment]
@dreampiggy I didn't create any raw podspec (in the Ruby format) for libwebp. I just used a json one which they published last (at that time) and iterated on that.

**Comment by dreampiggy** [comment]
OK...So we just keep that JSON format and keep maintain. Sounds a little interesting.

**Comment by dreampiggy** [comment]
@bpoplauschi  I created one `libwebp.podspec`, which is the Ruby DSL format. It produce the exact same result as currectly JSON format. And we'd better use that to upload to CocoaPods trunk instead.

See: [libwebp.podspec](https://github.com/SDWebImage/libwebp-Xcode/blob/master/libwebp.podspec), copy this file to the `webp` git repo, and run `pod trunk push`.

It produce the same result, except that the min deployment target version, the `null` value is not supported by Ruby DSL, use the minimum version for CocoaPods instead

```
➜ pod ipc spec libwebp.podspec > output.json
➜ diff output.json libwebp.podspec.json
18,21c18,21
<     "osx": "10.8",
<     "ios": "6.0",
<     "tvos": "9.0",
<     "watchos": "2.0"
---
>     "osx": null,
>     "ios": null,
>     "tvos": null,
>     "watchos": null
```

**Comment by bpoplauschi** [comment]
Nice job @dreampiggy 
Just out of curiosity, why do you think the Ruby DSL format is better than the json?

**Comment by dreampiggy** [comment]
@bpoplauschi JSON is the `Parsed result` of original Ruby DSL. For example

The DSL:

```ruby
s.source  = { :git => 'https://chromium.googlesource.com/webm/libwebp', :tag => 'v' + s.version.to_s }
```

When you want to upgrade, for DSL you just need to change `s.version = '1.1.0'`.  Because it automatically parse `v1.1.0` for Git Tag as well.

But however, for JSON, you need to change both Git Tag and version. This may be a little verbose and may be forgotten. 

And, for the subspecs, it's more easy to write in Ruby DSL, instead of JSON, which need you to nested JSON dict.

**Comment by bpoplauschi** [comment]
@dreampiggy since you added the `DSL` `podspec` to the repo, I think we can close the issue, right?
