### ISSUE TITLE
iOS 15 / Xcode 13 - min target conflict

### ISSUE THREAD

**Issue by AlexandreHauber** [SDWebImage/libwebp-Xcode#13]
Hey all!
We bumped our project to iOS 15 / Xcode 13, but we got the following on Jenkins:

`../SourcePackages/checkouts/libwebp-Xcode/Package.swift: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'libwebp' from project 'libwebp')` 

Can I open a PR with a min version bump?

Thanks!

**Comment by AlexandreHauber** [comment]
Just realized there are two PRs ([#11](https://github.com/SDWebImage/libwebp-Xcode/pull/11) & [#12](https://github.com/SDWebImage/libwebp-Xcode/pull/11)) related to that subject.

I will leave this open if you want to use this issue as reference for that PRs.

**Comment by dreampiggy** [comment]
Typically, we release new version based on libwebp Google release date.

We can bump the min deployment target version, however, for those user who still need lower version Xcode or have to deploy for iOS 8, this may be a pain.

Anyway, I can bump the podspec && carthage && swiftpm min deployment, and wait for next version release from libwebp Google upstream.

**Comment by dreampiggy** [comment]
Released [v1.2.1](https://github.com/SDWebImage/libwebp-Xcode/releases/tag/1.2.1)

**Comment by AlexandreHauber** [comment]
Nice, thank you for the support @dreampiggy !
