### ISSUE TITLE
call gif2webp from swift file

### ISSUE THREAD

**Issue by DanielZanchi** [SDWebImage/libwebp-Xcode#15]
I was able to add the package and call `WebPGetDecoderVersion()`
I would like to call the function to convert a GIF data to webp Data that is see in _gif2webp.c_

Would this be possible?

**Comment by dreampiggy** [comment]
I don't think `gif2webp` is library code

It's a executable command line, not available inside this `libwebp` libraray code

You can build yourself, check libwebp's official repo's README using cmake

**Comment by dreampiggy** [comment]
Because command line binary is only avaiable on macOS

I think using cmake to build is the simple way
