### ISSUE TITLE
Apple Privacy Manifest

### ISSUE THREAD

**Issue by carlosasmartins** [SDWebImage/libwebp-Xcode#19]
Apple is enforcing privacy manifests by Spring 2024, is this something on your radar? 🙏
https://developer.apple.com/news/?id=r1henawx

It's also listed in the required SDK to have privacy manifests: https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by dreampiggy** [comment]
I don't think I maintain libwebp. Ask Googler.
https://chromium.googlesource.com/webm/libwebp

**Comment by dreampiggy** [comment]
I don't think it's listed. Check again ?
