### ISSUE TITLE
A building error about inttypes.h.

### ISSUE THREAD

**Issue by SuperY** [SDWebImage/libwebp-Xcode#6]
If someone gets a building error about 'inttypes.h', replace 'inttypes.h' with 'xlocale/_inttypes.h' maybe make it works.

Error Messages:
...../Carthage/Build/iOS/libwebp.framework/Headers/types.h:20:10: Include of non-modular header inside framework module 'libwebp.types': '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/clang/include/inttypes.h'

**Comment by dreampiggy** [comment]
The CocoaPods version already fix this issue. This is actually a clang toolchain bug (`<inttypes.h>` is not a system clang module. Only `<stdint.h>` is. Suck)
