### ISSUE TITLE
podspec error.

### ISSUE THREAD

**Issue by weiguangmeng** [SDWebImage/libwebp-Xcode#7]
According to libwep.podspec,  src directory is not located at the current directory, when I use this pod library as a local pod. It will occur errors. when I move the src directory from libwebp directory to the current directory, it's ok.

**Comment by dreampiggy** [comment]
Why you think `src directory is not located at the current directory`. CocoaPods does not have this requirement that `Podspec must put into the same git root directory`.

If you really want to use as local pod, you can clone `https://github.com/webmproject/libwebp` and put podspec there to use. Or just point into the `libwebp-Xcode/libwebp` subdir to use.
