### ISSUE TITLE
Error while importing headers:  'webp/decode.h' file not found

### ISSUE THREAD

**Issue by roblabs** [SDWebImage/libwebp-Xcode#9]
The Swift Package Manager is used to pull `libwebp` into an Objective-C project.  When attempting to use import the headers, the search path doesn't appear to be used.

```C
#import <webp/decode.h>
```

---

* Is there a setting that needs to occur in the Target `Build Settings` to update either the *Header Search Path* or *User Header Search Paths*?
* Do you have a public Objective-C repo that makes use of Swift PM?
* The files under `include/web/*.h` are symbolic links back to `libwebp/src/webp/*.h` (which we also tried), is there an issue with Swift PM following those links?

---

The error is 

> `util/webp_reader.cpp:7:9: fatal error: 'webp/decode.h' file not found`
`#import <webp/decode.h>`

The project cannot use the preferred `@import libwebp`.  Thank you for supporting Swift PM in this project, as it is very useful.

**Comment by dreampiggy** [comment]
Use

```
#import <libwebp/decode.h>
```

**Comment by roblabs** [comment]
None of the following worked, all gave the error in Xcode,  Preprocessor error `file not found`



1.  `#import <libwebp/decode.h>`
1.  `#import <libwebp/webp/decode.h>`
1.  `#import <webp/decode.h>  // this the recommendation from the readme`

The `Package.swift` implies that the 3rd option, readme documentation, makes the most sense:

```
sources: ["libwebp/src"],
publicHeadersPath: "include",
```

---

https://github.com/SDWebImage/libwebp-Xcode/blob/master/Package.swift#L24,L30

**Comment by dreampiggy** [comment]
Maybe we should use the `@import libwebp`. Or custom the Swift Include Path for this..
